sudo: required
dist: trusty
language: node_js

node_js: "6.2.0"

services: 
  - mongodb
  - redis-server

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_install:
  - npm install -g gulp typings
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.0.5 mongodb-org-server=3.0.5 mongodb-org-shell=3.0.5 mongodb-org-mongos=3.0.5 mongodb-org-tools=3.0.5
 
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"   
  - sudo service mongod status
  - sleep 15  

script:
  - npm test

notifications:  
  email: false
