sudo: required
dist: trusty
language: node_js

node_js: "6.2.0"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

before_script:
  - npm install -g gulp
  - npm install -g typings
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - sleep 15
  - "mongo mydb_test --eval 'db.addUser("travis", "test");'"

script:
  - npm test

notifications:  
  email: false

services: 
  - mongodb
  - redis-server
