sudo: required
dist: trusty
language: node_js

node_js: "6.2.0"

services: 
  - mongodb
  - redis-server

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta
      
before_install:
  - npm install -g gulp typings
 
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" 
  - sleep 15  

script:
  - npm test

notifications:  
  email: false

